### ISSUE TITLE
relay claim sign issue

### ISSUE THREAD

**Issue by IronSight87** [ATOR-Development/ator-dashboard#127] opened 2023-10-21 13:18 UTC
**Description**
When claiming a new relay the sign message dialog appears endless. When I press „abort“ the overview with all my relays is gone. I have to reload the site and reconnect my wallet to see my relays again. The actual claim worked, but the UX is bad.

**Logs**

Sat, 21 Oct 2023 13:19:40 GMT | [INFO][RelayRegistry] Claiming fingerprint FFFFFFFFFFFFFFFFFFF
-- | --
Sat, 21 Oct 2023 13:19:42 GMT | [INFO][RelayRegistry] RelayRegistry refreshing for 0xFFFFFFFFFFFFFF
Sat, 21 Oct 2023 13:19:53 GMT | [ERROR][my-relays.vue] {"code":4001,"message":"User rejected the request.","stack":"construct@[native code]\nconstruct@[native code]\no@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:57:332\nconstruct@[native code]\n@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:2066:162\no@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:2066:840\nconstruct@[native code]\n@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:2066:162\no@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:2066:1361\nt@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:2070:271\n@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:4090:7248\nc@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:4090:511\nu@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:69:158\n@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:69:870\n@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:75:1471\nT@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:75:419\np@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:75:692\ncallReactNativeMicrotasks@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:75:2871\nvalue@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:37:2875\n@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:37:966\nvalue@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:37:2511\nvalue@/private/var/containers/Bundle/Application/D6AA2164-D13F-467A-9C63-05E0FB6B88BD/MetaMask.app/main.jsbundle:37:924\nvalue@[native code]\nvalue@[native code]"}

**Comment by jim-toth** [comment] 2023-10-21 22:34
Thanks for posting the logs, we're noticing that in recent versions of MetaMask it is firing everything 5x regardless of what it is.  For example, when we subscribe to EVM contract events we get 5 copies of the same event fired.  Similarly, when signing interactions, it's asking users to sign 5x.  What is interesting is that both of those situations arise from completely different code paths with the root cause being MetaMask itself.

We're going to investigate possible solutions to handle the odd behavior.

**Comment by jim-toth** [comment] 2023-10-21 22:41
Further investigation in #130

**Comment by jim-toth** [comment] 2023-10-22 03:06
There's an upcoming fix that should address this.  We'll keep this issue open until we know the fix is live.  #131

**Comment by IronSight87** [comment] 2023-10-22 07:13
Let me know as soon as the fix is deployed. Will test it and give feedback. Happy to help

**Comment by jim-toth** [comment] 2023-11-03 02:03
The fix for this should be live!  Please see my comment here https://github.com/ATOR-Development/ator-dashboard/issues/130#issuecomment-1791809222

If the duplicated signing issue persists we'll re-open and investigate.

**Closed by jim-toth** 2023-11-03 02:03 UTC
Labels: bug

**Comment by IronSight87** [comment] 2023-11-03 05:53
@jim-toth I can verify if fixed once https://github.com/ATOR-Development/ator-dashboard/issues/133 was fixed as my rewards can’t be loaded
